create table TM_ETL_NAME
(
	CAT	VARCHAR2(30),
	ETL_NAME VARCHAR2(30),
	WITH_SYNC NUMBER(1,0),                 -- 1:sync, 0: no sync
	CONSUMER_STATUS VARCHAR2(30),      		-- REGISTERED, STARTED, RECEVING, STOPPED 
	NOTE VARCHAR2(100),
	PRIMARY KEY (CAT,ETL_NAME)
)
