create table TM_HEALTH_SINK
(
	HEARTBEAT_TIME TIMESTAMP,
	INSERT_TIMESTAMP TIMESTAMP,
	UPDATE_TIMESTAMP TIMESTAMP,
	SCN NUMBER(19,0),
	COMMIT_SCN NUMBER(19,0),
	ROW_ID VARCHAR2(18 BYTE),
	PRIMARY KEY (HEARTBEAT_TIME)
)
