create table TM_LOGMINER_OFFSET
(
	START_TIME	TIMESTAMP,
	RESET_OFFSET	NUMBER(1,0),
	START_SCN	NUMBER(19,0),
	OFFSET_SCN	NUMBER(19,0),
	OFFSET_COMMIT_SCN	NUMBER(19,0),
	OFFSET_ROW_ID	VARCHAR2(18 BYTE),
	TABLE_WHITE_LIST	VARCHAR2(1000 BYTE),
	PRIMARY KEY (START_TIME)
)
