create table TM_HEALTH
(
	HEARTBEAT_TIME TIMESTAMP,
	CURRENT_SCN NUMBER(19,0),
	LOGMINER_SCN NUMBER(19,0),
	LOGMINER_RECEIVED TIMESTAMP,
	CONSUMER_RECEIVED TIMESTAMP,
	CONSUMER_CLIENT VARCHAR2(100),
	CPU_UTIL_VALUE NUMBER,
	PRIMARY KEY (HEARTBEAT_TIME)
)
