CREATE OR REPLACE PROCEDURE SP_INS_ETL_NAME (
	i_cat VARCHAR2,
	i_etl_name VARCHAR2,
	i_note VARCHAR2
) AS
BEGIN
  			
   insert into TM_ETL_NAME (CAT,ETL_NAME,WITH_SYNC,CONSUMER_STATUS,NOTE) 
   values(i_cat,i_etl_name,0,'REGISTERED',i_note);
   
END SP_INS_ETL_NAME;